_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "models/diffdet_coco_res50.pth"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 32
    NUM_CLASSES: 11
    SAMPLE_STEP: 4
    NUM_HEADS: 2
  ROI_HEADS:
    NUM_CLASSES: 11
DATASETS:
  TRAIN: ("Theme1_train",)
  TEST: ("Theme1_valid",)
SOLVER:
  BASE_LR: 1e-04
  BASE_LR_END: 5e-08
  STEPS: (7000, 9500)
  MAX_ITER: 10000
  WARMUP_ITERS: 500
TEST:
  DETECTIONS_PER_IMAGE: 32
  EVAL_PERIOD: 1000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
